"""Fix document storage URL column name

Revision ID: 002
Revises: 001
Create Date: 2024-01-01 01:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename s3_key to storage_url and change type
    op.alter_column('documents', 's3_key',
                    existing_type=sa.String(length=512),
                    new_column_name='storage_url',
                    existing_nullable=False,
                    type_=sa.String(length=1024))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert the changes
    op.alter_column('documents', 'storage_url',
                    existing_type=sa.String(length=1024),
                    new_column_name='s3_key',
                    existing_nullable=False,
                    type_=sa.String(length=512))
    # ### end Alembic commands ###